/*
 * This source file was generated by the Gradle 'init' task
 */
package serviciodeatencionalrestaurante;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
}
